### ISSUE TITLE
사용자 등록 

### ISSUE THREAD

**Issue by kayform** [kayform/DX-Management#1]
사용자 등록시 권한구분 field는 필수입력항목이 아니지만 빈값으로 등록시 '이 필드는 필수항목입니다'
에러 메시지 팝업됨

**Comment by happy6972** [comment]
권한구분 필드가 아니고 담당업무 필드임

**Comment by happy6972** [comment]
담당업무 필수입력항목으로 수정 필요

**Comment by happy6972** [comment]
필수 입력항목 수정완료  57820f2
